import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Providers from "./Providers";
import UpContainer from "./UpContainer";
import { UserProvider } from "./UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Providers>
            <UpContainer />
            {children}
          </Providers>
        </UserProvider>
      </body>
    </html>
  );
}
