import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import EndContainer from "./EndContainer";
import "./globals.css";
import UpContainer from "./UpContainer";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <Script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" strategy="beforeInteractive" />
        
      </head>
      <body>
        <UpContainer/>
        {children}
        <EndContainer/>
      </body>
    </html>
  );
}
